# Rozszerzenie docker-compose dla trybu deweloperskiego
version: '3.8'

services:
  php:
    environment:
      - CI_ENVIRONMENT=development
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    command: php-fpm -d display_errors=1 -d error_reporting=E_ALL

  nginx:
    volumes:
      - ./docker/nginx/dev.conf:/etc/nginx/conf.d/default.conf








